import type { getServerSideProps} from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import About from "../components/About";
import ContactMe from "../components/ContactMe";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import { PageInfo, Project, Skill, Social } from "../typings";
import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchProjects } from "../utils/fetchProjects";
import { fetchSkills } from "../utils/fetchSkills";
import {fetchSocial} from "../utils/fetchSocials"


type Props= {
 pageInfo:PageInfo;
  skills:Skill[];
  projects:Project[];
  socials:Social[];
}




const Home=({socials,pageInfo,projects,skills}:Props) => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80 z-0">
      <Head>
        <title>Divya&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials}/>
      {/* Hero */}
      <section id="hero" className="snap-start">
        <Hero pageInfo={pageInfo} />
      </section>
      {/* About */}
    <section id="about" className="snap-center">
      <About  pageInfo={pageInfo}/>
    </section>
      {/* Skills */}
      <section id="skills" className="snap-start">
      <Skills skills={skills}/>
    </section>
      {/* Projects */}
      <section id="projects" className="snap-start">
      <Projects projects={projects}/>
    </section>
      {/* Contact Me */}
      <section id="contact" className="snap-start">
      <ContactMe/>
    </section>

    <Link href="#hero">
    <footer className="sticky bottom-5 w-full cursor-pointer">
      <div className="flex items-center justify-center">
        <img className="rounded-full filter grayscale hover:grayscale-0 cursor-pointer h-10 w-10 object-cover
        "
        src="divya.JPG"
        alt="Picture of the author"
      
        />
      </div>
    </footer>
    </Link>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps<Props> = async()=>{
  const pageInfo:PageInfo= await fetchPageInfo();
  const skills:Skill[]= await fetchSkills();
  const projects:Project[]= await fetchProjects();
  const socials:Social[]= await fetchSocial();
  
  return{
    props:{
      pageInfo,
      skills,
      projects,
      socials
    },
  }
  }


